# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61e652546212c942472edf5d299c7adc84e5a7acf463f4264ce22774fb7e37e4aece26b52bab320e7a1fd7094d7987652454a057db11b6c63fd822175a99b000

test:
  secret_key_base: e926c3f7e088703e5b1714ec07ca93438649be055fe765773a7c0b32f30837257cbaeb315381cd84e9cdeb0af76f6e3b532881c7e3ccd540d7774f5ff49206ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
